siteTitle="freeCodeCamp Guide"
baseColor = "#006400"
linkPrefix = "/guide"
docPages = [
  "/docs/certificates-guide/",
  "/docs/certificates-guide/access-array-data-with-indexes/",
  "/docs/certificates-guide/access-multi-dimensional-arrays-with-indexes/",
  "/docs/certificates-guide/accessing-nested-arrays-in-json/",
]
